### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by jeffchulg** [bjyoungblood/BjyProfiler#16]
First of all, thank you for your module. It's fair and useful. I have 2 questions about it :

1) Why is your level of requirement set to 5.3.6 ? (I'm experiencing issues because the up2date version on my CentOS 5.8 server is 5.3.3 so I can't use your module)

2) Your module is the only one I've found which makes it possible to work with a Oracle Database. Is your adapter capable of working with Oracle Lobs ?

Thanks in advance.

**Comment by bjyoungblood** [comment]
1. In order to capture the stack trace of each query, I use debug_backtrace, but in order to be compatible with ZendDeveloperTools, the output of debug_backtrace has to be serializable. The only way to ensure that is to use the DEBUG_BACKTRACE_IGNORE_ARGS constant that was not defined until 5.3.6. Without the use of this constant, we will end up trying to serialize a PDO instance, which is not serializable. I've tried several ways to maintain this functionality while downgrading the requirement to 5.3.3, but the only thing I can think at this point would be to check the PHP version and only save the stack trace if running on 5.3.6+.
2. I don't think I know enough about Oracle or your setup in particular to answer fully. However, I can say that since PDO supports Oracle, you should be able to use a Zend\Db PDO adapter, though it may require some modification to use the ProfilingStatement and ProfilingAdapter classes I have set up in this module.

**Comment by jeffchulg** [comment]
as soon as I have been able to install my application on this server.. I can test it and report back all useful informations...
